### ISSUE TITLE
Crash on background with no matching scenario using wire protocol

### ISSUE THREAD

**Issue by tobhahn** [cucumber/cucumber#112]
Summary:
When using the wire protocol, cucumber exits with the fatal error ``undefined method `tag_names' for nil:NilClass (NoMethodError)`` when excluding scenarios by tag results in a feature with only a background.

Steps to reproduce:

* Place the following feature into a file ``no_matching_scenario.feature`` in ``legacy_features``

```gherkin
@wire
Feature: No matching scenario doesn't crash
  In order to be productive
  As a developer tagging new scenarios with @wip
  I want to be able to run cucumber even if none of my scenarios matches


  Background:
    Given a standard Cucumber project directory structure
    And a file named "features/step_definitions/some_remote_place.wire" with:
      """
      host: localhost
      port: 54321

      """

  Scenario: No matching scenarios
    Given a file named "features/wired.feature" with:
      """
        Feature: Wired wip with background

          Background:

          @wip
          Scenario:

      """
    And there is a wire server running on port 54321 which understands the following protocol:
      | request                                              | response                            |
      | ["step_matches",{"name_to_match":"we're all wired"}] | ["success",[{"id":"1", "args":[]}]] |
      | ["begin_scenario", {"tags":["bar","baz","foo"]}]     | ["success"]                         |
      | ["invoke",{"id":"1","args":[]}]                      | ["success"]                         |
      | ["end_scenario", {"tags":["bar","baz","foo"]}]       | ["success"]                         |
    When I run cucumber -f pretty -q -t ~@wip
    Then STDERR should be empty
    And it should pass with
      """
      Feature: Wired wip with background
      
        Background:

      0 scenarios
      0 steps

      """

```
* Run ``cucumber legacy_features/no_matching_scenario.feature``

Expected: 
No Error

Actual:

```
undefined method `tag_names' for nil:NilClass (NoMethodError)
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/feature_element.rb:70:in `source_tag_names'
/Users/toh/dev/cucumber/bin/../lib/cucumber/wire_support/wire_protocol/requests.rb:100:in `request_params'
/Users/toh/dev/cucumber/bin/../lib/cucumber/wire_support/wire_protocol/requests.rb:109:in `execute'
/Users/toh/dev/cucumber/bin/../lib/cucumber/wire_support/wire_protocol.rb:34:in `begin_scenario'
/Users/toh/dev/cucumber/bin/../lib/cucumber/wire_support/wire_language.rb:43:in `begin_scenario'
/Users/toh/dev/cucumber/bin/../lib/cucumber/wire_support/wire_language.rb:43:in `each'
/Users/toh/dev/cucumber/bin/../lib/cucumber/wire_support/wire_language.rb:43:in `begin_scenario'
/Users/toh/dev/cucumber/bin/../lib/cucumber/language_support/language_methods.rb:18:in `before'
/Users/toh/dev/cucumber/bin/../lib/cucumber/runtime/support_code.rb:107:in `send'
/Users/toh/dev/cucumber/bin/../lib/cucumber/runtime/support_code.rb:107:in `fire_hook'
/Users/toh/dev/cucumber/bin/../lib/cucumber/runtime/support_code.rb:106:in `each'
/Users/toh/dev/cucumber/bin/../lib/cucumber/runtime/support_code.rb:106:in `fire_hook'
/Users/toh/dev/cucumber/bin/../lib/cucumber/runtime.rb:103:in `before'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/background.rb:39:in `accept'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/background.rb:55:in `with_visitor'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/background.rb:38:in `accept'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/tree_walker.rb:57:in `visit_background'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/tree_walker.rb:163:in `broadcast'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/tree_walker.rb:56:in `visit_background'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/feature.rb:41:in `accept'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/tree_walker.rb:20:in `visit_feature'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/tree_walker.rb:163:in `broadcast'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/tree_walker.rb:19:in `visit_feature'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/features.rb:29:in `accept'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/features.rb:17:in `each'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/features.rb:17:in `each'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/features.rb:28:in `accept'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/tree_walker.rb:14:in `visit_features'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/tree_walker.rb:163:in `broadcast'
/Users/toh/dev/cucumber/bin/../lib/cucumber/ast/tree_walker.rb:13:in `visit_features'
/Users/toh/dev/cucumber/bin/../lib/cucumber/runtime.rb:45:in `run!'
/Users/toh/dev/cucumber/bin/../lib/cucumber/cli/main.rb:43:in `execute!'
/Users/toh/dev/cucumber/bin/../lib/cucumber/cli/main.rb:20:in `execute'
/Users/toh/dev/cucumber/bin/cucumber:14
```

**Comment by mattwynne** [comment]
As of 2.0 this is fixed.
