### ISSUE TITLE
json-to-messages generated ndjson file throws error "cannot read property 'status' of null

### ISSUE THREAD

**Issue by siva-sankaran** [cucumber/cucumber#1189]
## Summary

I am using cucumber-js 6.0.5. I want to generate a helpful human readable report. With the output of cucumber-js with legacy json formatter, I convert legacy json to cucumber-messages with npm package [json-to-messages](https://github.com/cucumber/cucumber/tree/master/json-to-messages/javascript)
```
$> cucumber-js --format json:report/report.json
$> cat report/report.json |  ./node_modules/.bin/json-to-features -i cucumber-js > messages.ndjson
$> cat messages.ndjson |  ./node_modules/.bin/cucumber-html-formatter  --format ndjson > log_output.html
C:\Source\bdd-project\node_modules\cucumber-query\src\CucumberQuery.ts:200
           if (message.testCaseFinished.testResult.status === undefined) {
                                                   ^
TypeError: Cannot read property 'status' of null
    at CucumberQuery.update (C:\Source\bdd-project\node_modules\cucumber-query\src\CucumberQuery.ts:200:47)
    at C:\Source\bdd-project\node_modules\cucumber-html-formatter\src\cli-main.tsx:41:21
    at Array.reduce (<anonymous>)
    at C:\Source\bdd-project\node_modules\cucumber-html-formatter\src\cli-main.tsx:40:44
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```

I tried to produce html from the ndjson file generated from [json-to-messages](https://github.com/cucumber/cucumber/tree/master/json-to-messages/javascript)  using [cucumber HTML Formatter](https://github.com/cucumber/cucumber/tree/master/html-formatter). But it throws error "Cannot read property 'status' of null"
## Expected Behavior

Given cucumber-js version 6.0.5 produce output in json format
When  json-to-messages npm package converts the output file to cucumber messages in ndjson 
And  cucumber HTML Formatter converts ndjson file into a html file
Then  html file should have all features that ran, their steps and its pass or fail status 

## Current Behavior

The ndjson file generated by  npm package [json-to-messages](https://github.com/cucumber/cucumber/tree/master/json-to-messages/javascript) is seems to be similar to other ndjson [file](https://github.com/cucumber/cucumber/blob/0ba63412cb8624cc21d2313db7a1b622a10e2112/compatibility-kit/javascript/features/examples-tables/examples-tables.ndjson) I found in cucumber repo .

`{"testCaseFinished":{"timestamp":{"seconds":"1600746814","nanos":102000000},"testCaseStartedId":"1f7c1559-28c2-45e2-ab82-1aec942f7c3a"}}`

Is cucumber-html-formatter expecting testResult property which has status property in above ndjson element ?
~~~
$> cat messages.ndjson |  ./node_modules/.bin/cucumber-html-formatter  --format ndjson > log_output.html
C:\Source\bdd-project\node_modules\cucumber-query\src\CucumberQuery.ts:200
           if (message.testCaseFinished.testResult.status === undefined) {
                                                   ^
TypeError: Cannot read property 'status' of null
    at CucumberQuery.update (C:\Source\bdd-project\node_modules\cucumber-query\src\CucumberQuery.ts:200:47)
    at C:\Source\bdd-project\node_modules\cucumber-html-formatter\src\cli-main.tsx:41:21
    at Array.reduce (<anonymous>)
    at C:\Source\bdd-project\node_modules\cucumber-html-formatter\src\cli-main.tsx:40:44
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
~~~

## Possible Solution

if the problem is in generated ndjson and not in cucumber html formatter, please point it so I could debug why json-to-messages didn't produce valid ndjson file.

## Steps to Reproduce (for bugs)

Please use this [file](https://gist.github.com/siva-sankaran/9fc712c2bc0ca773d3d04e696c843f06#file-messages-ndjson)  to generate html using cucumber html formatter CLI as follows

>$> cat messages.ndjson |  ./node_modules/.bin/cucumber-html-formatter  --format ndjson > log_output.html

## Context & Motivation

I can only use cucumbber-js  version 6.0.5.  I couldn't find where is the problem. Whether problem is output produced by cucumber-js or ndjson produced by json-to-messages npm package CLI or in cucumber html formatter cli

## Your Environment
* Version used: cucumbber-js v 6.0.5,  node V12.13.0
* Operating System and version: Windows 10

**Comment by siva-sankaran** [comment]
I tried to run cucumber html formatter cli against another ndjson [file ](https://github.com/cucumber/cucumber/blob/0ba63412cb8624cc21d2313db7a1b622a10e2112/compatibility-kit/javascript/features/examples-tables/examples-tables.ndjson) which I took from cucumber repo. It gaves same error.

**Comment by siva-sankaran** [comment]
After installing cucumber html formatter globally as mentioned [here](https://github.com/cucumber/cucumber/tree/master/html-formatter), I can successfully generate html report using global html formatter

> $>cat messages.ndjson |  cucumber-html-formatter  --format ndjson > log_output.html
