### ISSUE TITLE
python: CLI parser fails since tag v9.2.0

### ISSUE THREAD

**Issue by elchupanebrej** [cucumber/cucumber#1447]
## Summary: Python parser fails when trying to parse a feature

```
(gherkin-python) ➜  gherkin-python git:(4e6fb1a) ✗ ./bin/gherkin ./testdata/good/background.feature
Traceback (most recent call last):
  File "./bin/gherkin", line 26, in <module>
    for event in gherkin_events.enum(source_event):
  File "/Users/goloveshkokonstantin/Projects/gherkin-python/gherkin/stream/gherkin_events.py", line 35, in enum
    gherkin_document = self.parser.parse(source)
  File "/Users/goloveshkokonstantin/Projects/gherkin-python/gherkin/parser.py", line 79, in parse
    state = self.match_token(state, token, context)
  File "/Users/goloveshkokonstantin/Projects/gherkin-python/gherkin/parser.py", line 234, in match_token
    return state_map[state](token, context)
  File "/Users/goloveshkokonstantin/Projects/gherkin-python/gherkin/parser.py", line 653, in match_token_at_9
    if self.match_RuleLine(context, token):
  File "/Users/goloveshkokonstantin/Projects/gherkin-python/gherkin/parser.py", line 139, in match_RuleLine
    return self.handle_external_error(context, False, token, context.token_matcher.match_RuleLine)
AttributeError: 'TokenMatcher' object has no attribute 'match_RuleLine'
```

Nosetests are also failing 

# Env:
Testted against py27, py27,py36,py37,py38,py39
Tag >9.2.0 ; revision> 4e6fb1a2

**Comment by aurelien-reeves** [comment]
Hello @elchupanebrej ,
Thanks for your report.

Would you have more info about your issue? How could we reproduce it? On which version? Only gherkin@9.2, or it is still the case with latest version?

What does contain your .feature file?
