### ISSUE TITLE
react: start-storybook failing

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/cucumber#1488]
## Summary

From `react/javascript`, running the `storybook` script to do local development with storybook fails.

## Expected Behavior

Storybook runs normally.

## Current Behavior

~~~
/Users/davidgoss/Projects/cucumber/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13
    mainCompilation.fileSystemInfo.createSnapshot(
                                   ^

TypeError: Cannot read property 'createSnapshot' of undefined
    at /Users/davidgoss/Projects/cucumber/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13:36
    at new Promise (<anonymous>)
    at Object.createSnapshot (/Users/davidgoss/Projects/cucumber/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:12:10)
    at /Users/davidgoss/Projects/cucumber/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:219:35
~~~

## Possible Solution

This kind of thing often happens when multiple webpack versions are in `node_modules` and a plugin or loader picks up the wrong one because of how the hoisting has come out. Looks like it may be the case here due to storybook addons. From `npm ls webpack`:

```json
{
  "version": "0.0.0",
  "name": "@cucumber/cucumber-monorepo",
  "problems": [
    "invalid: webpack@5.30.0 /Users/davidgoss/Projects/cucumber/node_modules/webpack"
  ],
  "dependencies": {
    "@cucumber/html-formatter": {
      "version": "13.0.0",
      "resolved": "file:../../html-formatter/javascript",
      "dependencies": {
        "babel-loader": {
          "version": "8.2.2",
          "dependencies": {
            "webpack": {
              "version": "5.30.0"
            }
          }
        },
        "ts-loader": {
          "version": "8.1.0",
          "dependencies": {
            "webpack": {
              "version": "5.30.0"
            }
          }
        },
        "webpack-cli": {
          "version": "4.6.0",
          "dependencies": {
            "@webpack-cli/configtest": {
              "version": "1.0.2",
              "dependencies": {
                "webpack": {
                  "version": "5.30.0"
                }
              }
            },
            "webpack": {
              "version": "5.30.0"
            }
          }
        },
        "webpack": {
          "version": "5.30.0",
          "dependencies": {
            "terser-webpack-plugin": {
              "version": "5.1.1",
              "dependencies": {
                "webpack": {
                  "version": "5.30.0"
                }
              }
            }
          }
        }
      }
    },
    "@cucumber/react": {
      "version": "13.0.0",
      "resolved": "file:../../react/javascript",
      "dependencies": {
        "@storybook/addon-essentials": {
          "version": "6.2.3",
          "resolved": "https://registry.npmjs.org/@storybook/addon-essentials/-/addon-essentials-6.2.3.tgz",
          "dependencies": {
            "@storybook/addon-docs": {
              "version": "6.2.3",
              "resolved": "https://registry.npmjs.org/@storybook/addon-docs/-/addon-docs-6.2.3.tgz",
              "dependencies": {
                "@storybook/builder-webpack4": {
                  "version": "6.2.3",
                  "resolved": "https://registry.npmjs.org/@storybook/builder-webpack4/-/builder-webpack4-6.2.3.tgz",
                  "dependencies": {
                    "css-loader": {
                      "version": "3.6.0",
                      "resolved": "https://registry.npmjs.org/css-loader/-/css-loader-3.6.0.tgz",
                      "dependencies": {
                        "webpack": {
                          "version": "5.30.0"
                        }
                      }
                    },
                    "dotenv-webpack": {
                      "version": "1.8.0",
                      "resolved": "https://registry.npmjs.org/dotenv-webpack/-/dotenv-webpack-1.8.0.tgz",
                      "dependencies": {
                        "webpack": {
                          "version": "5.30.0",
                          "invalid": true,
                          "problems": [
                            "invalid: webpack@5.30.0 /Users/davidgoss/Projects/cucumber/node_modules/webpack"
                          ]
                        }
                      }
                    },
                    "html-webpack-plugin": {
                      "version": "4.5.2",
                      "resolved": "https://registry.npmjs.org/html-webpack-plugin/-/html-webpack-plugin-4.5.2.tgz",
                      "dependencies": {
                        "webpack": {
                          "version": "5.30.0"
                        }
                      }
                    },
                    "postcss-loader": {
                      "version": "4.2.0",
                      "resolved": "https://registry.npmjs.org/postcss-loader/-/postcss-loader-4.2.0.tgz",
                      "dependencies": {
                        "webpack": {
                          "version": "5.30.0"
                        }
                      }
                    },
                    "style-loader": {
                      "version": "1.3.0",
                      "resolved": "https://registry.npmjs.org/style-loader/-/style-loader-1.3.0.tgz",
                      "dependencies": {
                        "webpack": {
                          "version": "4.46.0"
                        }
                      }
                    },
                    "terser-webpack-plugin": {
                      "version": "3.1.0",
                      "resolved": "https://registry.npmjs.org/terser-webpack-plugin/-/terser-webpack-plugin-3.1.0.tgz",
                      "dependencies": {
                        "webpack": {
                          "version": "5.30.0"
                        }
                      }
                    },
                    "webpack-dev-middleware": {
                      "version": "3.7.3",
                      "resolved": "https://registry.npmjs.org/webpack-dev-middleware/-/webpack-dev-middleware-3.7.3.tgz",
                      "dependencies": {
                        "webpack": {
                          "version": "5.30.0"
                        }
                      }
                    },
                    "webpack-filter-warnings-plugin": {
                      "version": "1.2.1",
                      "resolved": "https://registry.npmjs.org/webpack-filter-warnings-plugin/-/webpack-filter-warnings-plugin-1.2.1.tgz",
                      "dependencies": {
                        "webpack": {
                          "version": "5.30.0",
                          "invalid": true,
                          "problems": [
                            "invalid: webpack@5.30.0 /Users/davidgoss/Projects/cucumber/node_modules/webpack"
                          ]
                        }
                      }
                    },
                    "webpack": {
                      "version": "4.46.0",
                      "resolved": "https://registry.npmjs.org/webpack/-/webpack-4.46.0.tgz",
                      "dependencies": {
                        "terser-webpack-plugin": {
                          "version": "1.4.5",
                          "resolved": "https://registry.npmjs.org/terser-webpack-plugin/-/terser-webpack-plugin-1.4.5.tgz",
                          "dependencies": {
                            "webpack": {
                              "version": "4.46.0"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "webpack": {
                  "version": "5.30.0"
                }
              }
            },
            "webpack": {
              "version": "5.30.0"
            }
          }
        },
        "@storybook/builder-webpack5": {
          "version": "6.2.3",
          "resolved": "https://registry.npmjs.org/@storybook/builder-webpack5/-/builder-webpack5-6.2.3.tgz",
          "dependencies": {
            "@storybook/core-common": {
              "version": "6.2.3",
              "resolved": "https://registry.npmjs.org/@storybook/core-common/-/core-common-6.2.3.tgz",
              "dependencies": {
                "webpack": {
                  "version": "4.46.0",
                  "resolved": "https://registry.npmjs.org/webpack/-/webpack-4.46.0.tgz",
                  "dependencies": {
                    "terser-webpack-plugin": {
                      "version": "1.4.5",
                      "resolved": "https://registry.npmjs.org/terser-webpack-plugin/-/terser-webpack-plugin-1.4.5.tgz",
                      "dependencies": {
                        "webpack": {
                          "version": "4.46.0"
                        }
                      }
                    }
                  }
                }
              }
            },
            "css-loader": {
              "version": "5.1.3",
              "dependencies": {
                "webpack": {
                  "version": "5.30.0"
                }
              }
            },
            "dotenv-webpack": {
              "version": "6.0.4",
              "dependencies": {
                "webpack": {
                  "version": "5.30.0"
                }
              }
            },
            "file-loader": {
              "version": "6.2.0",
              "dependencies": {
                "webpack": {
                  "version": "5.30.0"
                }
              }
            },
            "html-webpack-plugin": {
              "version": "5.3.1",
              "dependencies": {
                "webpack": {
                  "version": "5.30.0"
                }
              }
            },
            "terser-webpack-plugin": {
              "version": "5.1.1",
              "dependencies": {
                "webpack": {
                  "version": "5.30.0"
                }
              }
            },
            "url-loader": {
              "version": "4.1.1",
              "dependencies": {
                "webpack": {
                  "version": "5.30.0"
                }
              }
            },
            "webpack-dev-middleware": {
              "version": "4.1.0",
              "dependencies": {
                "webpack": {
                  "version": "5.30.0"
                }
              }
            },
            "webpack": {
              "version": "5.30.0"
            }
          }
        },
        "@storybook/react": {
          "version": "6.2.3",
          "resolved": "https://registry.npmjs.org/@storybook/react/-/react-6.2.3.tgz",
          "dependencies": {
            "@pmmmwh/react-refresh-webpack-plugin": {
              "version": "0.4.3",
              "dependencies": {
                "webpack": {
                  "version": "5.30.0"
                }
              }
            },
            "@storybook/core": {
              "version": "6.2.3",
              "resolved": "https://registry.npmjs.org/@storybook/core/-/core-6.2.3.tgz",
              "dependencies": {
                "@storybook/core-client": {
                  "version": "6.2.3",
                  "resolved": "https://registry.npmjs.org/@storybook/core-client/-/core-client-6.2.3.tgz",
                  "dependencies": {
                    "webpack": {
                      "version": "5.30.0"
                    }
                  }
                },
                "@storybook/core-server": {
                  "version": "6.2.3",
                  "resolved": "https://registry.npmjs.org/@storybook/core-server/-/core-server-6.2.3.tgz",
                  "dependencies": {
                    "style-loader": {
                      "version": "1.3.0",
                      "resolved": "https://registry.npmjs.org/style-loader/-/style-loader-1.3.0.tgz",
                      "dependencies": {
                        "webpack": {
                          "version": "4.46.0"
                        }
                      }
                    },
                    "webpack": {
                      "version": "4.46.0",
                      "resolved": "https://registry.npmjs.org/webpack/-/webpack-4.46.0.tgz",
                      "dependencies": {
                        "terser-webpack-plugin": {
                          "version": "1.4.5",
                          "resolved": "https://registry.npmjs.org/terser-webpack-plugin/-/terser-webpack-plugin-1.4.5.tgz",
                          "dependencies": {
                            "webpack": {
                              "version": "4.46.0"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            },
            "webpack": {
              "version": "4.46.0",
              "dependencies": {
                "terser-webpack-plugin": {
                  "version": "1.4.5",
                  "dependencies": {
                    "webpack": {
                      "version": "4.46.0"
                    }
                  }
                }
              }
            }
          }
        },
        "raw-loader": {
          "version": "4.0.2",
          "dependencies": {
            "webpack": {
              "version": "5.30.0"
            }
          }
        },
        "sass-loader": {
          "version": "11.0.1",
          "dependencies": {
            "webpack": {
              "version": "5.30.0"
            }
          }
        },
        "style-loader": {
          "version": "2.0.0",
          "dependencies": {
            "webpack": {
              "version": "5.30.0"
            }
          }
        }
      }
    }
  }
}
```

## Steps to Reproduce (for bugs)

1. `npm ci`
2. `cd react/javascript`
3. `npm run storybook`

Note that `build-storybook` is fine, and this won't cause issues with releases etc - best I can tell it's to do with a file watcher plugin.

**Comment by davidjgoss** [comment]
Specifically for `npm ls webpack@4`:

~~~
@cucumber/cucumber-monorepo@0.0.0 /Users/davidgoss/Projects/cucumber
└─┬ @cucumber/react@13.0.0 -> /Users/davidgoss/Projects/cucumber/react/javascript
  ├─┬ @storybook/addon-essentials@6.2.3
  │ └─┬ @storybook/addon-docs@6.2.3
  │   └─┬ @storybook/builder-webpack4@6.2.3
  │     ├─┬ style-loader@1.3.0
  │     │ └── webpack@4.46.0 deduped
  │     └─┬ webpack@4.46.0
  │       └─┬ terser-webpack-plugin@1.4.5
  │         └── webpack@4.46.0 deduped
  ├─┬ @storybook/builder-webpack5@6.2.3
  │ └─┬ @storybook/core-common@6.2.3
  │   └─┬ webpack@4.46.0
  │     └─┬ terser-webpack-plugin@1.4.5
  │       └── webpack@4.46.0 deduped
  └─┬ @storybook/react@6.2.3
    ├─┬ @storybook/core@6.2.3
    │ └─┬ @storybook/core-server@6.2.3
    │   ├─┬ style-loader@1.3.0
    │   │ └── webpack@4.46.0 deduped
    │   └─┬ webpack@4.46.0
    │     └─┬ terser-webpack-plugin@1.4.5
    │       └── webpack@4.46.0 deduped
    └─┬ webpack@4.46.0
      └─┬ terser-webpack-plugin@1.4.5
        └── webpack@4.46.0 deduped
~~~

**Comment by aurelien-reeves** [comment]
@davidjgoss I took a look as part of https://github.com/cucumber/cucumber/pull/1479

I've been able to make it work by removing the dependency to `@storybook/addon-essentials`

I am trying also to update storybook as the latest is 6.2.8
