### ISSUE TITLE
selenium 3 is throwing cucumberexception

### ISSUE THREAD

**Issue by analyst-anju** [cucumber/cucumber#181]
Selenium 3.3.1
Chrome driver 2.29
Chrome browser Version 57
Cucumber 1.2.5
The above set up is not launching Chrome browser and throwing following exception:

cucumber.runtime.CucumberException: Failed to instantiate class com.mycom.test.features_ui.ManageUserWebClientAccess

Is it a bug in selelnium or am I missing something. Please suggest.

**Comment by aslakhellesoy** [comment]
This doesn't sound line a bug.

Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

Please provide a full stack trace.

**Comment by analyst-anju** [comment]
The full trace is like this:

[31mcucumber.runtime.CucumberException: Failed to instantiate class com.mycom.test.features_ui.ManageUserWebClientAccess
      	at cucumber.runtime.java.DefaultJavaObjectFactory.cacheNewInstance(DefaultJavaObjectFactory.java:47)
      	at cucumber.runtime.java.DefaultJavaObjectFactory.getInstance(DefaultJavaObjectFactory.java:33)
      	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
      	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
      	at cucumber.runtime.Runtime.runStep(Runtime.java:300)
      	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
      	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
      	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
      	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
      	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
      	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
      	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
      	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
      	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
      	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
      	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
      	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
      	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
      	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
      	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
      	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
      	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
      	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
      	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
      	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
      	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
      	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
      	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
      	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
      	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
      	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
      	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
      	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
      Caused by: java.lang.reflect.InvocationTargetException
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
      	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
      	at cucumber.runtime.java.DefaultJavaObjectFactory.cacheNewInstance(DefaultJavaObjectFactory.java:41)
