### ISSUE TITLE
cucumber-expressions-javascript: regular expressions defaulting to strings?

### ISSUE THREAD

**Issue by tony-kerz** [cucumber/cucumber#265]
## Summary

what would be the idiomatic way to support a regular expression match for string results?

i read the documentation around custom-types (e.g. color = red|blue|yellow),
and i have a similar requirement, but i don't need a custom type, string is fine.

i tried something like:
```
'we (POST|PUT|PATCH) {string} with body:'
```
but the regular expression wasn't respected and i received complaints like:
```
? When we HTTP POST "/" with body:
       """
       {_id: '3'}
       """
       Undefined. Implement with the following snippet:

         When('we HTTP POST {string} with body:', function (string, docString, callback) {
           // Write code here that turns the phrase above into concrete actions
           callback(null, 'pending');
         });
```
should i just go the "custom type" route, where my custom type is just a string, or is there an easier way?

**Comment by tony-kerz** [comment]
on a related note, how would i get a reference to `parameterTypeRegistry`...?
i tried the following unsuccessfully:
```
import {defineSupportCode, parameterTypeRegistry, ParameterType} from 'cucumber'

parameterTypeRegistry.defineParameterType(
  new ParameterType(
    'verb', // name
    /POST|PUT|PATCH/, // regexp
    String, // type
    s => s, // transform
    false, // useForSnippets
    true // preferForRegexpMatch
  )
)
```

**Comment by aslakhellesoy** [comment]
First, let's analyse the following Cucumber Expression: `we (POST|PUT|PATCH) {string} with body:`.

The parenthesis means that the literal text inside is optional, which means it will match `we  "xxxx" with body:` and `we POST|PUT|PATCH "xxxx" with body:`, but not `we POST "xxxx" with body:`.

[Defining a parameter type](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md#defineparametertypename-preferforregexpmatch-regexp-transformer-useforsnippets) for HTTP verbs is the correct thing to do here:

```javascript
import { defineParameterType } from 'cucumber'

defineParameterType({
  name: 'verb', 
  regexp: /POST|PUT|PATCH/, 
  transformer: s => s
})
```

The following undefined step:

```gherkin
When we HTTP POST "/" with body
```

would print the a snippet with the following Cucumber Expression:

```
we HTTP {verb} {string} with body
```

I hope this clears it up. Please reopen or comment if not.

**Comment by tony-kerz** [comment]
thanks aslak, good point on the regex being optional, that isn't the desired effect.

i'm still having trouble getting this to work.

currently my code looks something like:
```
import {defineSupportCode, defineParameterType} from 'cucumber'
//...
defineParameterType({
  name: 'verb',
  regexp: /POST|PUT|PATCH/
  transformer: s => s
})
//...
defineSupportCode(({Given, When, Then}) => {
  When('we HTTP {verb} {string} with body:', async function(method, path, bodyString) {
    //...
  })
}
```
which yields:
```
Error: Undefined parameter type {verb}
    at UndefinedParameterTypeError.CucumberExpressionError (/Users/tony/git/node-cuke-helpr/node_modules/cucumber-expressions/dist/errors.js:17:131)
    at new UndefinedParameterTypeError (/Users/tony/git/node-cuke-helpr/node_modules/cucumber-expressions/dist/errors.js:67:139)
    at new CucumberExpression (/Users/tony/git/node-cuke-helpr/node_modules/cucumber-expressions/dist/cucumber_expression.js:45:33)
    at StepDefinition.getCucumberExpression (/Users/tony/git/node-cuke-helpr/node_modules/cucumber/src/models/step_definition.js:52:14)
    at StepDefinition.matchesStepName (/Users/tony/git/node-cuke-helpr/node_modules/cucumber/src/models/step_definition.js:63:37)
    at /Users/tony/git/node-cuke-helpr/node_modules/cucumber/src/runtime/test_case_runner.js:99:29
    at Array.filter (<anonymous>)
    at TestCaseRunner.getStepDefinitions (/Users/tony/git/node-cuke-helpr/node_modules/cucumber/src/runtime/test_case_runner.js:98:52)
    at /Users/tony/git/node-cuke-helpr/node_modules/cucumber/src/runtime/test_case_runner.js:61:36
    at Array.forEach (<anonymous>)
    at TestCaseRunner.emitPrepared (/Users/tony/git/node-cuke-helpr/node_modules/cucumber/src/runtime/test_case_runner.js:60:32)
    at TestCaseRunner.<anonymous> (/Users/tony/git/node-cuke-helpr/node_modules/cucumber/src/runtime/test_case_runner.js:154:10)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/Users/tony/git/node-cuke-helpr/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/Users/tony/git/node-cuke-helpr/node_modules/bluebird/js/release/generators.js:97:49)
    at TestCaseRunner.<anonymous> (/Users/tony/git/node-cuke-helpr/node_modules/bluebird/js/release/generators.js:201:15)
```
can you spot where i went astray?
