### ISSUE TITLE
Unhandled rejection Error: empty stack in cucumber-expressions@5.0.2 (javascript)

### ISSUE THREAD

**Issue by dherges** [cucumber/cucumber#296]
## Summary

Tests stopped working with following error:

```
Unhandled rejection Error: empty stack
    at pop (/root/repo/node_modules/cucumber-tag-expressions/lib/tag_expression_parser.js:82:35)
    at TagExpressionParser.parse (/root/repo/node_modules/cucumber-tag-expressions/lib/tag_expression_parser.js:52:16)
    at new PickleFilter (/root/repo/node_modules/cucumber/src/pickle_filter.js:14:52)
    at Cli.<anonymous> (/root/repo/node_modules/cucumber/src/cli/index.js:90:21)
    at next (native)
```

Cucumber versions are:

```
cucumber-expressions@^5.0.0:
  version "5.0.2"
  resolved "https://registry.yarnpkg.com/cucumber-expressions/-/cucumber-expressions-5.0.2.tgz#f4e03c2698bd43e92011a055d9c4ce57718b91b0"
cucumber@^3.0.0:
  version "3.0.6"
  resolved "https://registry.yarnpkg.com/cucumber/-/cucumber-3.0.6.tgz#87f140b7c8dbf54904782730e25dcc450bed7db5"
```

## Expected Behavior

```gherkin
Feature: Home

  Scenario: A first scenario
    When I open the page
    Then I see a player list with 3 persons
```

## Current Behavior

```
Unhandled rejection Error: empty stack
    at pop (/root/repo/node_modules/cucumber-tag-expressions/lib/tag_expression_parser.js:82:35)
    at TagExpressionParser.parse (/root/repo/node_modules/cucumber-tag-expressions/lib/tag_expression_parser.js:52:16)
    at new PickleFilter (/root/repo/node_modules/cucumber/src/pickle_filter.js:14:52)
    at Cli.<anonymous> (/root/repo/node_modules/cucumber/src/cli/index.js:90:21)
    at next (native)
```

## Possible Solution

....

## Steps to Reproduce (for bugs)

Link to CI failure: https://circleci.com/gh/spektrakel-blog/ng-testing-snippets/85

## Context & Motivation

Is it a regression introduced by minor/major version bump?

The dependency in package.json is:

```json
"cucumber": "^3.0.0"
```

## Your Environment

* Version used: see above
* Operating System and version: running CI builds in container https://github.com/alexeagle/ngcontainer 
* Link to your project: https://github.com/spektrakel-blog/ng-testing-snippets

**Comment by aslakhellesoy** [comment]
Looks like you're passing a malformed tag expression to `--tags`. Can you tell us what it is?

**Comment by dherges** [comment]
In the above project, it's running cucumber through protractor.

Is it this empty `tags: []` configuration?

https://github.com/spektrakel-blog/ng-testing-snippets/blob/406e57106801761280cc38803b1ee697ba919514/protractor.conf.js#L24-L29

**Comment by aslakhellesoy** [comment]
That's probably it. We need to improve the error message. In the meanwhile, try removing it.

**Comment by dherges** [comment]
Yes, commenting out the empty `tags: []` [fixes the test run](https://circleci.com/gh/spektrakel-blog/ng-testing-snippets/88):

```
[07:38:38] I/launcher - Running 1 instances of WebDriver
[07:38:38] I/direct - Using ChromeDriver directly...
.[HPM] Rewriting path from "/api/players" to "/players"
[HPM] GET /api/players ~> http://localhost:3000
..

1 scenario (1 passed)
2 steps (2 passed)
0m00.396s
[07:38:40] I/launcher - 0 instance(s) of WebDriver still running
[07:38:40] I/launcher - chrome #01 passed
```

The unfortunate thing is that the error is introduced by upgrading from `cucumber@3.0.3` to `cucumber@3.0.6` (a fix version bump), but the major version bump of cucumber-tag-expressions comes transitive in.
