### ISSUE TITLE
Escaped backslash breaks regex capture group

### ISSUE THREAD

**Issue by dan-nawrocki** [cucumber/cucumber#323]
## Summary
Escaping a backslash before a regex capture group breaks the parsing in tree_regexp.rb.

## Expected Behavior
```
Then(/foo\\(bar|baz)/) do |verb|
end
```
should be used to match `foo\bar` or `foo\baz`.

## Current Behavior
The following error is thrown:
```
bad value for range (ArgumentError)
$HOME/.rvm/gems/ruby-2.4.1/gems/cucumber-expressions-5.0.7/lib/cucumber/cucumber_expressions/tree_regexp.rb:24:in `block in initialize'
$HOME/.rvm/gems/ruby-2.4.1/gems/cucumber-expressions-5.0.7/lib/cucumber/cucumber_expressions/tree_regexp.rb:15:in `each'
$HOME/.rvm/gems/ruby-2.4.1/gems/cucumber-expressions-5.0.7/lib/cucumber/cucumber_expressions/tree_regexp.rb:15:in `each_with_index'
$HOME/.rvm/gems/ruby-2.4.1/gems/cucumber-expressions-5.0.7/lib/cucumber/cucumber_expressions/tree_regexp.rb:15:in `initialize'
$HOME/.rvm/gems/ruby-2.4.1/gems/cucumber-expressions-5.0.7/lib/cucumber/cucumber_expressions/regular_expression.rb:12:in `new'
$HOME/.rvm/gems/ruby-2.4.1/gems/cucumber-expressions-5.0.7/lib/cucumber/cucumber_expressions/regular_expression.rb:12:in `initialize'
$HOME/.rvm/gems/ruby-2.4.1/gems/cucumber-3.1.0/lib/cucumber/glue/registry_and_more.rb:154:in `new'
$HOME/.rvm/gems/ruby-2.4.1/gems/cucumber-3.1.0/lib/cucumber/glue/registry_and_more.rb:154:in `create_expression'
$HOME/.rvm/gems/ruby-2.4.1/gems/cucumber-3.1.0/lib/cucumber/glue/step_definition.rb:30:in `new'
$HOME/.rvm/gems/ruby-2.4.1/gems/cucumber-3.1.0/lib/cucumber/glue/registry_and_more.rb:82:in `register_rb_step_definition'
$HOME/.rvm/gems/ruby-2.4.1/gems/cucumber-3.1.0/lib/cucumber/glue/dsl.rb:30:in `register_rb_step_definition'
$HOME/.rvm/gems/ruby-2.4.1/gems/cucumber-3.1.0/lib/cucumber/glue/dsl.rb:132:in `register_rb_step_definition'
```

## Workaround
Add square brackets around the escaped backslash:
```
Then(/foo[\\](bar|baz)/) do |verb|
end
```

**Comment by aslakhellesoy** [comment]
Fixed in `cucumber-expressions` `5.0.10`.

@dan-nawrocki could you confirm that it works for you please?

**Comment by nijikon** [comment]
I'm not sure, but I think that this change introduced an error in my use case.
```ruby
Then(/^(a|\d) (\w+) severity (\w+) should be created$/) do |number, severity, resource|
```
/cc @aslakhellesoy

**Comment by nijikon** [comment]
OK, was an issue on my end, changing that line to
```ruby
Then(/^(a|\d+) (\w+) severity (\w+) should be created$/) do |number, severity, resource|
```
fixed the issue. The interesting thing is that it worked on version `5.0.7`.

**Comment by aslakhellesoy** [comment]
Can you try 5.0.12?

If that doesn’t work can you tell us what the error is?

**Comment by aslakhellesoy** [comment]
@nijikon there was another regression in 5.0.12. Try 5.0.13, which should fix the issue.

Sorry about all the regressions in the past few days - it's not trivial to get this stuff right. 5.0.13 simplified some of the code that went in post 5.0.7, so hopefully things are more stable now.

**Comment by dan-nawrocki** [comment]
@aslakhellesoy I can confirm 5.0.13 works for me. Thanks for the quick fix!
