### ISSUE TITLE
cucumber-expressions-javascript: 5.0.10 gives 'TypeError: Cannot read property 'add' of undefined'

### ISSUE THREAD

**Issue by martinwilkerson-scisys** [cucumber/cucumber#325]
## Summary

v5.0.10 of cucumber-expressions is giving an error when running cucumber.

## Expected Behavior

Tests should run.

## Current Behavior

A TypeError occurs:

~~~
$ node --harmony ./node_modules/.bin/cucumber
TypeError: Cannot read property 'add' of undefined
    at /home/vagrant/selenium_test/node_modules/cucumber-expressions/dist/src/tree_regexp.js:38:34
    at Array.forEach (native)
    at new TreeRegexp (/home/vagrant/selenium_test/node_modules/cucumber-expressions/dist/src/tree_regexp.js:24:31)
    at new RegularExpression (/home/vagrant/selenium_test/node_modules/cucumber-expressions/dist/src/regular_expression.js:17:24)
    at StepDefinition.getCucumberExpression (/home/vagrant/selenium_test/node_modules/cucumber/lib/models/step_definition.js:79:16)
    at StepDefinition.matchesStepName (/home/vagrant/selenium_test/node_modules/cucumber/lib/models/step_definition.js:93:37)
    at Array.filter (native)
    at /home/vagrant/selenium_test/node_modules/cucumber/lib/runtime/test_case_runner.js:107:38
    at Array.forEach (native)
    at TestCaseRunner.emitPrepared (/home/vagrant/selenium_test/node_modules/cucumber/lib/runtime/test_case_runner.js:106:34)
    at TestCaseRunner.<anonymous> (/home/vagrant/selenium_test/node_modules/cucumber/lib/runtime/test_case_runner.js:216:14)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/vagrant/selenium_test/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/vagrant/selenium_test/node_modules/bluebird/js/release/generators.js:97:49)
    at TestCaseRunner.<anonymous> (/home/vagrant/selenium_test/node_modules/bluebird/js/release/generators.js:201:15)
    at Runtime.<anonymous> (/home/vagrant/selenium_test/node_modules/cucumber/lib/runtime/index.js:113:51)
~~~

## Steps to Reproduce (for bugs)

1. Create a step definition with the following expression `/^I go to '\/(.+)'$/`
2. Run cucumber

## Context & Motivation

I'm trying to use regular expressions to define step matches with parameters in capturing groups.

## Your Environment

* Version used: Cucumber v3.2.1, cucumber-expressions v5.0.10
* Operating System and version: Ubuntu 16.04

**Comment by aslakhellesoy** [comment]
Thanks for the report. I've reproduced it on my end. Working on a fix!

**Comment by aslakhellesoy** [comment]
FWIW it's a regression introduced by #324

**Comment by aslakhellesoy** [comment]
This was surprising:

```
ruby -e "puts /^I go to '\/(.+)'$/.source"
^I go to '/(.+)'$

node -e "console.log(/^I go to '\/(.+)'$/.source)"
^I go to '\/(.+)'$
```

I understand why `/` needs to be escaped (because of the `//` regexp literal syntax), but I had not expected to see the escape character in the source! It's not there in Ruby, but it is in JavaScript.

Oh well - fixed now. Release coming shortly.

**Comment by aslakhellesoy** [comment]
5.0.11 is out - can you try that please @martinwilkerson-scisys?

**Comment by martinwilkerson-scisys** [comment]
Can confirm 5.0.11 fixes the issue. Thank you very much, that was a very speedy resolution!
