### ISSUE TITLE
Better error when both DataTable and DocString supplied (was: Arity mismatch discrepancy)

### ISSUE THREAD

**Issue by kevlarC** [cucumber/cucumber#56]
Using version 1.2.4 JVM in junit with either java/scala

Consider this piece of Gherkin.

```
 When  I POST a request to /some/url with:
      | header        | value            |
      | SomeHeader    | value            |
      | AnotherHeader | value2           |
      | Content-Type  | application/json |
    """
    {
       "member": "value",
       "member": "value2"
    }
    """
```

And this step method in scala (the same thing happens in java)

``` scala
  When(s"^I POST a request to ([^ ]*) with:") { (url: String, body: String, headers: DataTable) =>
      println( headers )
      println( url )
      println( body )
  }
```

the error is:

```

cucumber.runtime.CucumberException: Arity mismatch: Step Definition 'Quote.scala:13' with pattern [^I POST a request to ([^ ]*) with:] is declared with 3 parameters. However, the gherkin step has 3 arguments [/v4/quote/create, DocString:{
   "till": "GB:a_store_id:a_till_id",
   "currency": "GBP"
}, Table:[[header, value], [TraceId, a_trace_id], [ClientId, a_client_id:a_secret], [Authorization, Bearer:temporary_token], [Content-Type, application/json]]]. 
Step: When I POST a request to /v4/quote/create with:
    at cucumber.runtime.StepDefinitionMatch.arityMismatch(StepDefinitionMatch.java:102)
    at cucumber.runtime.StepDefinitionMatch.transformedArgs(StepDefinitionMatch.java:60)
    at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
    at cucumber.runtime.Runtime.runStep(Runtime.java:299)
    at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
    at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
    at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
    at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
    at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
    at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
```

Two issues arise 
1) is this valid gherkin ?
2) the error message obviously is incorrect saying all three parameters are there and it requires 3 parameters ?

Looking at the code it seems to be either of these two lines:
1) in release 1.2.4 lines 53-57 StepDefinitionMatch.java  arityMismatch()

```
       if (step.getRows() != null) {
            argumentCount++;
        } else if (step.getDocString() != null) {
            argumentCount++;
        }
```

if the gherkin is correct then this should be a if and then another if not if/else. The parameters might need fixing later on to get the correct items in place.

2) or 114-116 Ste[DefinitionMatch.java arityMismatch. This should be the same as in 1) i.e. either if/else or if if. Ideally this should use exactly the same code to avoid this bug in the future.

**Comment by aslakhellesoy** [comment]
You can't have both a data table and a doc string - only one of them. The fix would be to throw an error explaining that more clearly.

**Comment by aslakhellesoy** [comment]
This issue was moved to cucumber/cucumber-jvm#1183
