### ISSUE TITLE
datatable is not working with groovy script

### ISSUE THREAD

**Issue by seenimurugans** [cucumber/cucumber#569]
## Summary

Datatble is not converting to Map properly if i use groovy script for my step definition. But there is no issue if i use normal groovy/java8 class

I created the sample project in github [github link](https://github.com/seenimurugans/cucumberDatatable )

## Expected Behavior

datatable should automatically convert to Map as per the documentation. Please run the example provided in the github link [link](https://github.com/seenimurugans/cucumberDatatable)

## Current Behavior

~~~
cucumber.runtime.CucumberException: Could not convert arguments for step [^I have the below parameters passed$] defined at 'DataTableStepdefs.groovy:6'.
The details are in the stacktrace below.
        at cucumber.runner.PickleStepDefinitionMatch.couldNotConvertArguments(PickleStepDefinitionMatch.java:69)
        at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:46)
        at cucumber.runner.TestStep.executeStep(TestStep.java:63)
        at cucumber.runner.TestStep.run(TestStep.java:49)
        at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
        at cucumber.runner.TestCase.run(TestCase.java:44)
        at cucumber.runner.Runner.runPickle(Runner.java:40)
        at cucumber.runtime.Runtime$1.run(Runtime.java:84)
        at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:220)
        at cucumber.runtime.Runtime.run(Runtime.java:81)
        at cucumber.api.cli.Main.run(Main.java:26)
        at cucumber.api.cli.Main.main(Main.java:8)
Caused by: io.cucumber.datatable.CucumberDataTableException: Can't convert DataTable to Map<java.lang.String, java.lang.String>. There is more then one value per key. Did you mean to transform to Map<java.lang.String, List<java.lang.String>> instead?
        at io.cucumber.datatable.CucumberDataTableException.cantConvertToMap(CucumberDataTableException.java:25)
        at io.cucumber.datatable.CucumberDataTableException.keyValueMismatchException(CucumberDataTableException.java:42)
        at io.cucumber.datatable.DataTableTypeRegistryTableConverter.toMap(DataTableTypeRegistryTableConverter.java:212)
        at io.cucumber.datatable.DataTableTypeRegistryTableConverter.convert(DataTableTypeRegistryTableConverter.java:66)
        at io.cucumber.datatable.DataTable.convert(DataTable.java:362)
        at io.cucumber.stepexpression.StepExpressionFactory$3.transform(StepExpressionFactory.java:73)
        at io.cucumber.stepexpression.DeArgument.getValue(DataTableArgument.java:19)
        at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:41)
        ... 10 more

:cucumber FAILED

FAILURE: Build failed with an exception.

~~~

## Steps to Reproduce (for bugs)

I provided the [github link](https://github.com/seenimurugans/cucumberDatatable) with Readme file which explains how to run the project. 

When i run the project i see the exception instead to see the passed test results.

## Context & Motivation

I wanted to use groovy script rather than java class as groovy is far better/matured than Java

## Your Environment

* Version used: 
        cucumberVersion = '4.2.0'
	groovyVersion = '2.5.6'

* Operating System and version: mac
* Link to your project: [Link](https://github.com/seenimurugans/cucumberDatatable)

**Comment by seenimurugans** [comment]
I raised in cucumber-jvm project instead.
