### ISSUE TITLE
cucumber-expressions: All regex lookarounds are incorrectly counted as a capturing group causing an iterator overflow and a NoSuchElement Exception.

### ISSUE THREAD

**Issue by benariss** [cucumber/cucumber#643]
## Summary

When using any lookaround (positive lookahead '(?=..', negative lookahead '(?!..', negative lookbehind '(?<!..' or positive lookbehind '(?<=..') in a regular expression Cucumber will encounter a NoSuchElement exception when trying to parse a matching gherkin.  This is the same issue described in #481 and fixed for negative lookaheads in #593 and is being caused by Cucumber treating the lookaheads as a capturing group causing a mismatch between the number of groups to process and the iterator count causing it to overflow and trigger the exception.

## Expected Behavior

Cucumber should be able to successfully parse a regex match which contains any lookaround group.

## Current Behavior

Currently if you use any of the regex lookaround groups Cucumber treats them as a capture group, requiring you to add a parameter to the step definition for them.  
This also causes a discrepancy between the number of capture groups to be processed and the number of group iterations that are performed causing the iterator to overflow and the following exception stacktrace:

~~~
java.util.NoSuchElementException
	at io.cucumber.cucumberexpressions.TreeRegexp$IntRange.next(TreeRegexp.java:99)
	at io.cucumber.cucumberexpressions.TreeRegexp$IntRange.next(TreeRegexp.java:82)
	at io.cucumber.cucumberexpressions.GroupBuilder.build(GroupBuilder.java:18)
	at io.cucumber.cucumberexpressions.GroupBuilder.build(GroupBuilder.java:21)
	at io.cucumber.cucumberexpressions.TreeRegexp.match(TreeRegexp.java:75)
	at io.cucumber.cucumberexpressions.Argument.build(Argument.java:12)
	at io.cucumber.cucumberexpressions.RegularExpression.match(RegularExpression.java:54)
	at io.cucumber.stepexpression.StepExpression.match(StepExpression.java:22)
	at io.cucumber.stepexpression.ExpressionArgumentMatcher.argumentsFrom(ExpressionArgumentMatcher.java:21)
	at cucumber.runtime.java.JavaStepDefinition.matchedArguments(JavaStepDefinition.java:62)
	at cucumber.runner.Glue.stepDefinitionMatches(Glue.java:105)
	at cucumber.runner.Glue.stepDefinitionMatch(Glue.java:87)
	at cucumber.runner.Runner.addTestStepsForPickleSteps(Runner.java:64)
	at cucumber.runner.Runner.createTestCaseForPickle(Runner.java:54)
	at cucumber.runner.Runner.runPickle(Runner.java:39)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:122)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:64)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:131)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
	at ✽.foo is a big bar(file:src/test/resources/features/TestRegexLookaround.feature:4)
~~~

## Possible Solution

The expression parsing in TreeRegexp should be modified to identify all lookaround groups as non-capturing.

## Steps to Reproduce (for bugs)

1. Create a step definition using regex that includes a lookaround group.  Note that you need to add a parameter for the lookaround group in order for it to match.
```java
@Given("foo is a (?=[bar])(.*)$")
public void givenFooIsBar(Object lookaroundGroup, String bar) {
	System.out.println("Captured " + bar);
}
```
2. Create a scenario to test the step.
```
Scenario: Test regex parse failure
Given foo is a big bar
```
3. Execute the test and observe the raised exception.

## Your Environment

* Version used: 4.2.6
* Operating System and version: MacOS Mojave v10.14.5

## Related Issues
Issue #481 
PR #593

**Comment by adam-zjy** [comment]
Could you also considered the regex like ?> or ?+
