### ISSUE TITLE
Cucumber forces Integer type on a \d+ capture group

### ISSUE THREAD

**Issue by yktoo** [cucumber/cucumber#658]
#  Summary

The compatibility with previous version(s) is broken.

A step definition that uses `(\d+)` capture group forces the method have an `Integer` (or `int`) argument. Previously a `String` would do fine.

Example code:
```java
@When("^I type (\\d+) into input field$")
public void register(String value) {
...
```

## Expected Behavior

The typed value is converted into a `String`, just like it was previously (tested with info.cukes.cucumber-java v1.2.5)

## Current Behavior

An exception is thrown:
```
cucumber.runtime.CucumberException: Failed to invoke nl.ns.cucumber.LoketdienstSteps.register(String) in file:[...path...], caused by java.lang.IllegalArgumentException: argument type mismatch
	at cucumber.runtime.Utils$1.call(Utils.java:29)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:20)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:57)
	at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)
	at cucumber.runner.TestStep.executeStep(TestStep.java:65)
	at cucumber.runner.TestStep.run(TestStep.java:50)
	at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
	at cucumber.runner.TestCase.run(TestCase.java:46)
	at cucumber.runner.Runner.runPickle(Runner.java:50)
	at cucumber.runtime.Runtime$1.run(Runtime.java:104)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:258)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at cucumber.runtime.Runtime.run(Runtime.java:101)
	at io.cucumber.core.cli.Main.run(Main.java:43)
	at io.cucumber.core.cli.Main.main(Main.java:14)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:26)
	... 17 more

```

## Context & Motivation

This is particularly bad since it would try to convert whatever is given, for example, providing `2222222222` (which is too big for an Integer) results in:

```
cucumber.runtime.CucumberException: Could not convert arguments for step [...] defined at '...'.
The details are in the stacktrace below.
	at cucumber.runner.PickleStepDefinitionMatch.couldNotConvertArguments(PickleStepDefinitionMatch.java:69)
	at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:46)
	at cucumber.runner.TestStep.executeStep(TestStep.java:65)
	at cucumber.runner.TestStep.run(TestStep.java:50)
	at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
	at cucumber.runner.TestCase.run(TestCase.java:46)
	at cucumber.runner.Runner.runPickle(Runner.java:50)
	at cucumber.runtime.Runtime$1.run(Runtime.java:104)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:258)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at cucumber.runtime.Runtime.run(Runtime.java:101)
	at io.cucumber.core.cli.Main.run(Main.java:43)
	at io.cucumber.core.cli.Main.main(Main.java:14)
Caused by: io.cucumber.cucumberexpressions.CucumberExpressionException: ParameterType {int} failed to transform [2222222222] to class java.lang.Integer
	at io.cucumber.cucumberexpressions.ParameterType.transform(ParameterType.java:190)
	at io.cucumber.cucumberexpressions.Argument.getValue(Argument.java:64)
	at io.cucumber.stepexpression.ExpressionArgument.getValue(ExpressionArgument.java:15)
	at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:41)
	... 13 more
Caused by: java.lang.NumberFormatException: For input string: "2222222222"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.valueOf(Integer.java:740)
	at java.lang.Integer.decode(Integer.java:1197)
	at io.cucumber.cucumberexpressions.BuiltInParameterTransformer.transform(BuiltInParameterTransformer.java:51)
	at io.cucumber.cucumberexpressions.ParameterTypeRegistry$5.transform(ParameterTypeRegistry.java:70)
	at io.cucumber.cucumberexpressions.ParameterTypeRegistry$5.transform(ParameterTypeRegistry.java:67)
	at io.cucumber.cucumberexpressions.ParameterType$TransformerAdaptor.transform(ParameterType.java:215)
	at io.cucumber.cucumberexpressions.ParameterType.transform(ParameterType.java:186)
	... 16 more
```

## Your Environment

* Cucumber 4.6.0
* Java 8

**Comment by mpkorstanje** [comment]
I think #659 is a good solution but I'm going to let it percolate a bit. The short version:

If we have a matching regex and it's of the right type, use that. If not treat it as an anonymous parameter type. 

There is a flag to override this behavior. This flag is off for all basic types. But will be on for all user defined parameter types. This solution assumes that if you are using regex and you define a parameter type you really want that type.

I'm not sure if this assumption is correct.

> This will be a fun one to fix!

I hope

**Comment by mpkorstanje** [comment]
Pushed the wrong branch.
