### ISSUE TITLE
'Too many open files' when running cuke suite

### ISSUE THREAD

**Issue by coderkind** [cucumber/cucumber#667]
Hi @mattwynne,

as discussed over at https://github.com/BBC-News/responsive-news/issues/2238, this is raising the issue where running a suite of cukes results in a 'Too many open files - getcwd (Errno::EMFILE)' error.

As requested, here are the dumps of the contrasting passing and failing suites for separate developers.

PASSING
```
GEM
  remote: https://rubygems.org/
  specs:
    active_support (3.0.0)
      activesupport (= 3.0.0)
    activesupport (3.0.0)
    addressable (2.3.5)
    anmo (0.0.30)
      dalli
      httparty
      rack
      thin
    awesome_print (1.2.0)
    builder (3.2.2)
    capybara (2.1.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-mechanize (1.1.0)
      capybara (~> 2.1.0)
      mechanize (~> 2.7)
    childprocess (0.5.1)
      ffi (~> 1.0, >= 1.0.11)
    chunky_png (1.3.0)
    cliver (0.3.2)
    coderay (1.1.0)
    cucumber (1.3.12)
      builder (>= 2.1.2)
      diff-lcs (>= 1.1.3)
      gherkin (~> 2.12)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.1)
    daemons (1.1.9)
    dalli (2.7.0)
    diff-lcs (1.2.5)
    domain_name (0.5.16)
      unf (>= 0.0.5, < 1.0.0)
    eventmachine (1.0.3)
    exifr (1.1.3)
    ffi (1.9.3)
    fspath (2.1.0)
    gherkin (2.12.2)
      multi_json (~> 1.3)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    httparty (0.13.0)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.6.9)
    image_optim (0.12.1)
      exifr (~> 1.1.3)
      fspath (~> 2.1.0)
      image_size (~> 1.2.0)
      in_threads (~> 1.2.0)
      progress (~> 3.0.0)
    image_size (1.2.0)
    in_threads (1.2.0)
    iniparse (1.1.6)
    json (1.8.1)
    mechanize (2.7.3)
      domain_name (~> 0.5, >= 0.5.1)
      http-cookie (~> 1.0)
      mime-types (~> 2.0)
      net-http-digest_auth (~> 1.1, >= 1.1.1)
      net-http-persistent (~> 2.5, >= 2.5.2)
      nokogiri (~> 1.4)
      ntlm-http (~> 0.1, >= 0.1.1)
      webrobots (>= 0.0.9, < 0.2)
    method_source (0.8.2)
    mime-types (2.2)
    mini_portile (0.5.2)
    multi_json (1.9.0)
    multi_test (0.1.1)
    multi_xml (0.5.5)
    net-http-digest_auth (1.4)
    net-http-persistent (2.9.4)
    net-ssh (2.8.0)
    nokogiri (1.6.1)
      mini_portile (~> 0.5.0)
    ntlm-http (0.1.1)
    poltergeist (1.5.0)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
    progress (3.0.0)
    pry (0.9.12.6)
      coderay (~> 1.0)
      method_source (~> 0.8)
      slop (~> 3.4)
    rack (1.5.2)
    rack-test (0.6.2)
      rack (>= 1.0)
    rake (10.1.1)
    rest-client (1.6.7)
      mime-types (>= 1.16)
    rspec (2.14.1)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
    rspec-core (2.14.8)
    rspec-expectations (2.14.5)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-mocks (2.14.6)
    rubyzip (1.1.1)
    sass (3.3.0)
      rake
    selenium-webdriver (2.40.0)
      childprocess (>= 0.5.0)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0.4)
    slop (3.5.0)
    thin (1.6.2)
      daemons (>= 1.0.9)
      eventmachine (>= 1.0.0)
      rack (>= 1.0.0)
    unf (0.1.3)
      unf_ext
    unf_ext (0.0.6)
    webrobots (0.1.1)
    websocket (1.0.7)
    websocket-driver (0.3.2)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  active_support
  addressable
  anmo
  awesome_print
  capybara (~> 2.1.0)
  capybara-mechanize
  chunky_png
  cucumber
  httparty
  i18n
  image_optim
  iniparse
  json
  net-ssh
  nokogiri
  poltergeist
  pry
  rake
  rest-client
  rspec
  sass (= 3.3.0)
  selenium-webdriver
```

FAILING
```
GEM
  remote: https://rubygems.org/
  specs:
    active_support (3.0.0)
      activesupport (= 3.0.0)
    activesupport (3.0.0)
    addressable (2.3.6)
    anmo (0.0.30)
      dalli
      httparty
      rack
      thin
    awesome_print (1.2.0)
    builder (3.2.2)
    capybara (2.1.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-mechanize (1.1.0)
      capybara (~> 2.1.0)
      mechanize (~> 2.7)
    childprocess (0.5.2)
      ffi (~> 1.0, >= 1.0.11)
    chunky_png (1.3.0)
    cliver (0.3.2)
    coderay (1.1.0)
    cucumber (1.3.14)
      builder (>= 2.1.2)
      diff-lcs (>= 1.1.3)
      gherkin (~> 2.12)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.1)
    daemons (1.1.9)
    dalli (2.7.0)
    diff-lcs (1.2.5)
    domain_name (0.5.18)
      unf (>= 0.0.5, < 1.0.0)
    eventmachine (1.0.3)
    exifr (1.1.3)
    ffi (1.9.3)
    fspath (2.1.0)
    gherkin (2.12.2)
      multi_json (~> 1.3)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    httparty (0.13.1)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.6.9)
    image_optim (0.13.1)
      exifr (~> 1.1.3)
      fspath (~> 2.1.0)
      image_size (~> 1.3.0)
      in_threads (~> 1.2.0)
      progress (~> 3.0.0)
    image_size (1.3.0)
    in_threads (1.2.1)
    iniparse (1.3.2)
    json (1.8.1)
    mechanize (2.7.3)
      domain_name (~> 0.5, >= 0.5.1)
      http-cookie (~> 1.0)
      mime-types (~> 2.0)
      net-http-digest_auth (~> 1.1, >= 1.1.1)
      net-http-persistent (~> 2.5, >= 2.5.2)
      nokogiri (~> 1.4)
      ntlm-http (~> 0.1, >= 0.1.1)
      webrobots (>= 0.0.9, < 0.2)
    method_source (0.8.2)
    mime-types (2.2)
    mini_portile (0.5.3)
    multi_json (1.9.2)
    multi_test (0.1.1)
    multi_xml (0.5.5)
    net-http-digest_auth (1.4)
    net-http-persistent (2.9.4)
    net-ssh (2.8.0)
    nokogiri (1.6.1)
      mini_portile (~> 0.5.0)
    ntlm-http (0.1.1)
    poltergeist (1.5.0)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
    progress (3.0.0)
    pry (0.9.12.6)
      coderay (~> 1.0)
      method_source (~> 0.8)
      slop (~> 3.4)
    rack (1.5.2)
    rack-test (0.6.2)
      rack (>= 1.0)
    rake (10.3.0)
    rest-client (1.6.7)
      mime-types (>= 1.16)
    rspec (2.14.1)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
    rspec-core (2.14.8)
    rspec-expectations (2.14.5)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-mocks (2.14.6)
    rubyzip (1.1.3)
    sass (3.3.0)
      rake
    selenium-webdriver (2.41.0)
      childprocess (>= 0.5.0)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0.4)
    slop (3.5.0)
    thin (1.6.2)
      daemons (>= 1.0.9)
      eventmachine (>= 1.0.0)
      rack (>= 1.0.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.6)
    webrobots (0.1.1)
    websocket (1.0.7)
    websocket-driver (0.3.2)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  active_support
  addressable
  anmo
  awesome_print
  capybara (~> 2.1.0)
  capybara-mechanize
  chunky_png
  cucumber
  httparty
  i18n
  image_optim
  iniparse
  json
  net-ssh
  nokogiri
  poltergeist
  pry
  rake
  rest-client
  rspec
  sass (= 3.3.0)
  selenium-webdriver
```

**Comment by jmoody** [comment]
I have encountered something appears to be related to this.

I will be happy to open a new issue or append an existing one.  I can also provide a full stack trace.

I came to this issue after reviewing **Remove unnecessary `multi_test` require** #750.

> Could this be a Ruby 2.0 bug?

@mattwynne Your Ruby 2.0 bug prompted me to check ruby 2.2.0 vs. 2.1.3.


#### 2.2.0

```
|2.2.0| (master)
$ be cucumber --version
1.3.18
$ be cucumber -p ios
Using the ios, ios_common, common, ios_tags and ios_requires profiles...
@test @wip
Feature: Chat Room

  Background: I am logged in and looking at the home page # features/chatroom.feature:5
undefined method `extend_world' for nil:NilClass (NoMethodError)
/Users/moody/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/multi_test-0.1.1/lib/multi_test.rb:31:in `extend_with_best_assertion_library'
/Users/moody/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cucumber-1.3.18/lib/cucumber/rb_support/rb_language.rb:121:in `extend_world'
/Users/moody/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cucumber-1.3.18/lib/cucumber/rb_support/rb_language.rb:67:in `begin_rb_scenario'
```

#### 2.1.3

```
|2.1.3| (master)
$ be cucumber --version
1.3.18
$ be cucumber -p ios
# Works as expected.
```

The respective Gemfile.lock files have only this diff:

```
$ diff 2.2.0.lock 2.1.3.lock
81a82
>       json (~> 1.4)
```

This forum post mentions the same problem I am seeing. 

* https://groups.google.com/forum/#!topic/cukes/1MD-xGSSukc

**Comment by mattwynne** [comment]
@coderkind I'd love to know whether upgrading your version of Ruby fixed this. I'm going to close this since you have a workaround, unless you have any objections.
