### ISSUE TITLE
I am trying to launch chrome browser using selenium and cucumber framework  getting issue like java.lang.NoSuchFieldError: INSTANCE

### ISSUE THREAD

**Issue by roop152** [cucumber/cucumber#701]
_I am using below versions of selenium java and server and cucumber dependencies.

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.47.1</version>
		</dependency> 

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>2.47.1</version>
		</dependency>

		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>0.1.0</version>
		</dependency>

<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.1.8</version>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.5</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-core</artifactId>
			<version>1.1.8</version>
		</dependency>

<dependency>
			<groupId>com.theoryinpractise</groupId>
			<artifactId>cucumber-testng-factory</artifactId>
			<version>1.0.1</version>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-html</artifactId>
			<version>0.2.6</version>
		</dependency>

But, If i am using same versions of jar files in ant and trying to launch chrome browser it is working.

If i am using same version of dependencies in maven getting issue for launching chrome browser.

Getting below error for maven:- 

java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:72)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:84)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:59)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:487)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:147)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:136)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:112)
	at org.openqa.selenium.remote.internal.HttpClientFactory.getClientConnectionManager(HttpClientFactory.java:74)
	at org.openqa.selenium.remote.internal.HttpClientFactory.<init>(HttpClientFactory.java:57)
	at org.openqa.selenium.remote.internal.HttpClientFactory.<init>(HttpClientFactory.java:60)
	at org.openqa.selenium.remote.internal.ApacheHttpClient$Factory.getDefaultHttpClientFactory(ApacheHttpClient.java:252)
	at org.openqa.selenium.remote.internal.ApacheHttpClient$Factory.<init>(ApacheHttpClient.java:229)
	at org.openqa.selenium.remote.HttpCommandExecutor.getDefaultClientFactory(HttpCommandExecutor.java:96)
	at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:70)
	at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:58)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.<init>(DriverCommandExecutor.java:49)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:138)
	at framework.Lib.Common.WebCtrlOperations.GetWebDriver(WebCtrlOperations.java:136)
	at defFiles.SalesForce.launchSF(SalesForce.java:45)
	at ✽.Given I launch salesforce test portal(D:/D2_FrameWork/Salesforce_Automation/src/test/resources/FeatureFiles/A22B_Product_Name_Family/New_Product_Name_Family_Qualifier_Achievement.feature:5)_

**Comment by luke-hill** [comment]
As mentioned by a fellow maintainer in the previous similar thread. There could be a number of reasons and without an MVCE we cannot triage.

What I will say here is that cucumber is not a browser automation tool. So your efforts might be better served asking on the selenium issue tracker, but they will also want an MVCE. ideally in the form of a github repo.

**Comment by aslakhellesoy** [comment]
I'm closing this since the error is not related to Cucumber

**Comment by roop152** [comment]
May i know, What purpose of Git hub portal is Available.
As soon as i am posting an issue, People are closing an issue.

**Comment by aslakhellesoy** [comment]
@roop152 we only use GitHub issues to track Cucumber bugs and contributions.

Please use the [support](https://cucumber.io/support) forums for questions and discussions about Cucumber.

For questions about other tools like Selenium WebDriver we encourage users to use their dedicated forums.
