### ISSUE TITLE
js_dsl.js:3: syntax error, unexpected '{', expecting keyword_then or ';' or '\n'

### ISSUE THREAD

**Issue by zedtux** [cucumber/cucumber#759]
Suddenly I'm starting to have this exception:

```
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/js_support/js_dsl.js:3: syntax error, unexpected '{', expecting keyword_then or ';' or '\n'
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/js_support/js_dsl.js:6: syntax error, unexpected keyword_else, expecting '}'
    else{
        ^
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/js_support/js_dsl.js:7: syntax error, unexpected ';', expecting =>
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/js_support/js_dsl.js:13: syntax error, unexpected ',', expecting end-of-input (SyntaxError)
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `block in load'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/js_support/js_language.rb:114:in `initialize'
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/runtime/support_code.rb:74:in `new'
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/runtime/support_code.rb:74:in `load_programming_language'
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/runtime/support_code.rb:194:in `programming_language_for'
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/runtime/support_code.rb:178:in `load_file'
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/runtime/support_code.rb:82:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/runtime.rb:184:in `load_step_definitions'
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/runtime.rb:42:in `run!'
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/lib/cucumber/cli/main.rb:47:in `execute!'
/usr/local/lib/ruby/gems/2.1.0/gems/cucumber-1.3.17/bin/cucumber:13:in `<top (required)>'
/usr/local/bin/cucumber:23:in `load'
/usr/local/bin/cucumber:23:in `<main>'
Coverage report generated for Cucumber Features to /application/coverage. 325 / 438 LOC (74.2%) covered.
```

As you can see, I'm using the latest version of cucumber (version 1.3.17) and Ruby 2.1.2 within a Rails 4 project (4.1.6) with the cucumber-rails gem version 1.4.0.

I'm using Javascript all the time:

env.rb:

```
Capybara.default_driver = :poltergeist
```

Let me know if I can tell more in order to help on this ?

**Comment by mattwynne** [comment]
Closing. Anyone with this issue please upgrade to v 2.0.0.rc.4 or higher

**Comment by zedtux** [comment]
Thank you @mattwynne
