### ISSUE TITLE
Cucumber doesn't work with JUnit 4.12

### ISSUE THREAD

**Issue by lbeuster** [cucumber/cucumber#791]
Since the JUnit 4.12 runners now have more validation the ExamplesRunner of Cucumber causes an exception because it's not public.

Unfortunately the original exception can only be seen while debugging. Could be that Cucumber violates the JUnit contract of initialization errors, because it wraps the InitializationError in a CucumberException. If Cucumber would rethrow the original InitializationError then we could see the original exception in the JUnit reporting (see ErrorReportingRunner of JUnit).

cucumber.runtime.CucumberException: Failed to create scenario runner
	at cucumber.runtime.junit.FeatureRunner.buildFeatureElementRunners(FeatureRunner.java:85)
	at cucumber.runtime.junit.FeatureRunner.<init>(FeatureRunner.java:31)
	at cucumber.api.junit.Cucumber.addChildren(Cucumber.java:106)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:62)
        ...
Caused by: org.junit.runners.model.InitializationError
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:418)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
	at org.junit.runners.Suite.<init>(Suite.java:112)
	at cucumber.runtime.junit.ExamplesRunner.<init>(ExamplesRunner.java:21)
	at cucumber.runtime.junit.ScenarioOutlineRunner.<init>(ScenarioOutlineRunner.java:24)
	at cucumber.runtime.junit.FeatureRunner.buildFeatureElementRunners(FeatureRunner.java:81)
	... 21 more

**Comment by lbeuster** [comment]
sorry, wrong project ;)

**Comment by aslakhellesoy** [comment]
The cucumber-jvm project has a PR for this
