### ISSUE TITLE
ruby 2.2.0 + cucumber 1.3.18 raises undefined method `extend_world' for nil:NilClass

### ISSUE THREAD

**Issue by jmoody** [cucumber/cucumber#798]
* MacOS Yosemite
* rbenv

#### 2.2.0

```
|2.2.0| (master)
$ be cucumber --version
1.3.18
$ be cucumber -p ios
Using the ios, ios_common, common, ios_tags and ios_requires profiles...
@test @wip
Feature: Chat Room

  Background: I am logged in and looking at the home page # features/chatroom.feature:5
undefined method `extend_world' for nil:NilClass (NoMethodError)
2.2.0:multi_test-0.1.1/lib/multi_test.rb:31:in `extend_with_best_assertion_library'
2.2.0:cucumber-1.3.18/lib/cucumber/rb_support/rb_language.rb:121:in `extend_world'
2.2.0:cucumber-1.3.18/lib/cucumber/rb_support/rb_language.rb:67:in `begin_rb_scenario'
```

#### 2.1.3

```
|2.1.3| (master)
$ be cucumber --version
1.3.18
$ be cucumber -p ios
# Works as expected.
```

The respective Gemfile.lock files have only this diff:

```
$ diff 2.2.0.lock 2.1.3.lock
81a82
>       json (~> 1.4)
```

### Links

* [Forum post mentioning this issue](https://groups.google.com/forum/#!topic/cukes/1MD-xGSSukc)
* **Support ruby 2.2 for 1.3.x** #774
* **Use 2.2 on travis** #783

#### Stack Trace

```
undefined method `extend_world' for nil:NilClass (NoMethodError)
2.2.0:multi_test-0.1.1/lib/multi_test.rb:31:in `extend_with_best_assertion_library'
2.2.0:cucumber-1.3.18/lib/cucumber/rb_support/rb_language.rb:121:in `extend_world'
2.2.0:cucumber-1.3.18/lib/cucumber/rb_support/rb_language.rb:67:in `begin_rb_scenario'
2.2.0:cucumber-1.3.18/lib/cucumber/rb_support/rb_language.rb:101:in `begin_scenario'
2.2.0:cucumber-1.3.18/lib/cucumber/language_support/language_methods.rb:14:in `before'
2.2.0:cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:112:in `block in fire_hook'
2.2.0:cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:111:in `each'
2.2.0:cucumber-1.3.18/lib/cucumber/runtime/support_code.rb:111:in `fire_hook'
2.2.0:cucumber-1.3.18/lib/cucumber/runtime.rb:107:in `before'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/background.rb:42:in `block in accept'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/background.rb:57:in `with_visitor'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/background.rb:41:in `accept'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:64:in `block in visit_background'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:63:in `visit_background'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/feature.rb:36:in `accept'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:27:in `block in visit_feature'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:26:in `visit_feature'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/features.rb:28:in `block in accept'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/features.rb:17:in `each'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/features.rb:17:in `each'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/features.rb:27:in `accept'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:21:in `block in visit_features'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:170:in `broadcast'
2.2.0:cucumber-1.3.18/lib/cucumber/ast/tree_walker.rb:20:in `visit_features'
2.2.0:cucumber-1.3.18/lib/cucumber/runtime.rb:49:in `run!'
2.2.0:cucumber-1.3.18/lib/cucumber/cli/main.rb:47:in `execute!'
2.2.0:cucumber-1.3.18/bin/cucumber:13:in `<top (required)>'
2.2.0:bin/cucumber:23:in `load'
2.2.0:bin/cucumber:23:in `<main>'
```

**Comment by jmoody** [comment]
`bundle exec rake` is failing locally with ruby 2.2.0 and passing with ruby 2.1.3.  It seems to match the behavior seen on travis.

I am willing try my hand at a fix, but is this hopelessly complex?

**Comment by mattwynne** [comment]
Thanks. I think this needs to be raised on the multi_test gem, which AFAIK doesn’t have Ruby 2.2. compatibility yet.

https://github.com/cucumber/multi_test

**Comment by jmoody** [comment]
Ah, is this because ruby 2.2 removed 'minitest' and 'test-unit' from the stdlib?

I've forked multi_test and will take a look.

**Comment by tooky** [comment]
I've added travis directives for ruby 2.2, and its failing but I haven't
had time to look into what's causing this.

@jmoody I think you're right the problem will be related to removing
minitest / test_unit from the standard library. Thanks for taking a
look.

**Comment by jmoody** [comment]
@tooky 

It is definitely the root-cause of the problem. 

I can get the multi_tests to pass with a simple fix, but I believe this just hides the problem.

Shall I close this issue and open a new one in multi_test?

**Comment by tooky** [comment]
@jmoody yes please!

**Comment by tooky** [comment]
@jmoody you should be able to `bundle update multi_test` and it should fixes your issue.

**Comment by jmoody** [comment]
Thanks @tooky.  I have been advising clients to include multi_test in their Gemiles when migrating to ruby 2.2.0.

**Comment by mattwynne** [comment]
@tooky can we close this ticket then?

**Comment by tooky** [comment]
@mattwynne yes - we should probably release a new version of 1.3.x too - that depends on the fixed version of MultiTest

**Comment by jmoody** [comment]
Thanks @tooky + @mattwynne.

I am sorry I could not finish what I started.

**Comment by mattwynne** [comment]
Please don't be sorry @jmoody - bug reports and feedback are still really valuable work. Thanks!

**Comment by tooky** [comment]
@jmoody +1 :bow:
