### ISSUE TITLE
Cucumber 2.0.0.rc.3 crashes with Ruby 1.9.3-p448/Ruby 2.0.0-p247

### ISSUE THREAD

**Issue by jfinkhaeuser** [cucumber/cucumber#805]
This cropped up while investigating #804 further.

```bash
$ gem install cucumber --version '= 2.0.0.rc.3'
Fetching: cucumber-core-1.0.0.gem (100%)
Fetching: cucumber-2.0.0.rc.3.gem (100%)
Successfully installed cucumber-core-1.0.0
Successfully installed cucumber-2.0.0.rc.3
2 gems installed
Installing ri documentation for cucumber-core-1.0.0...
Installing ri documentation for cucumber-2.0.0.rc.3...
Installing RDoc documentation for cucumber-core-1.0.0...
Installing RDoc documentation for cucumber-2.0.0.rc.3...
$ cucumber --version
/home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0.rc.3/lib/cucumber/multiline_argument/data_table.rb:49:in `<class:DataTable>': uninitialized constant Cucumber::MultilineArgument::DataTable::Forwardable (NameError)
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0.rc.3/lib/cucumber/multiline_argument/data_table.rb:25:in `<module:MultilineArgument>'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0.rc.3/lib/cucumber/multiline_argument/data_table.rb:5:in `<module:Cucumber>'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0.rc.3/lib/cucumber/multiline_argument/data_table.rb:4:in `<top (required)>'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0.rc.3/lib/cucumber/multiline_argument.rb:2:in `<top (required)>'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0.rc.3/lib/cucumber/step_match.rb:1:in `<top (required)>'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0.rc.3/lib/cucumber/language_support/language_methods.rb:1:in `<top (required)>'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0.rc.3/lib/cucumber/runtime.rb:9:in `<top (required)>'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0.rc.3/lib/cucumber.rb:6:in `<top (required)>'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0.rc.3/lib/cucumber/cli/main.rb:8:in `<top (required)>'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /home/jens/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/cucumber-2.0.0.rc.3/bin/cucumber:7:in `<top (required)>'
	from /home/jens/.rbenv/versions/1.9.3-p448/bin/cucumber:23:in `load'
	from /home/jens/.rbenv/versions/1.9.3-p448/bin/cucumber:23:in `<main>'
```

Works fine with Ruby 2.0.0-p247.

**Comment by jfinkhaeuser** [comment]
I lie. It doesn't work with Ruby 2.0.0-p247. Same problem.

```bash
$ cucumber --version
/home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.rc.3/lib/cucumber/multiline_argument/data_table.rb:49:in `<class:DataTable>': uninitialized constant Cucumber::MultilineArgument::DataTable::Forwardable (NameError)
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.rc.3/lib/cucumber/multiline_argument/data_table.rb:25:in `<module:MultilineArgument>'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.rc.3/lib/cucumber/multiline_argument/data_table.rb:5:in `<module:Cucumber>'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.rc.3/lib/cucumber/multiline_argument/data_table.rb:4:in `<top (required)>'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.rc.3/lib/cucumber/multiline_argument.rb:2:in `<top (required)>'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.rc.3/lib/cucumber/step_match.rb:1:in `<top (required)>'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.rc.3/lib/cucumber/language_support/language_methods.rb:1:in `<top (required)>'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.rc.3/lib/cucumber/runtime.rb:9:in `<top (required)>'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.rc.3/lib/cucumber.rb:6:in `<top (required)>'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.rc.3/lib/cucumber/cli/main.rb:8:in `<top (required)>'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
	from /home/jens/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/cucumber-2.0.0.rc.3/bin/cucumber:7:in `<top (required)>'
	from /home/jens/.rbenv/versions/2.0.0-p247/bin/cucumber:23:in `load'
	from /home/jens/.rbenv/versions/2.0.0-p247/bin/cucumber:23:in `<main>'
```

**Comment by jfinkhaeuser** [comment]
I have a simple patch for it (next), for now here's the list of gems actually used:

cucumber-core-1.0.0
builder-3.2.2
multi_test-0.1.1
cucumber-2.0.0.rc.3
psych-2.0.1
multi_json-1.10.1
gherkin-2.12.2
json-1.8.2

That's on Linux 3.13.0-43-generic #72-Ubuntu SMP x86_64 GNU/Linux

**Comment by jfinkhaeuser** [comment]
```diff
--- old/data_table.rb	2015-02-13 13:55:22.584327486 +0100
+++ new/data_table.rb	2015-02-13 14:10:38.140377212 +0100
@@ -1,5 +1,6 @@
 require 'gherkin/formatter/escaping'
 require 'cucumber/core/ast/describes_itself'
+require 'forwardable'
 
 module Cucumber
   module MultilineArgument
@@ -46,7 +47,7 @@
 
       include Enumerable
       include Core::Ast::DescribesItself
-      extend Forwardable
+      extend ::Forwardable
 
       NULL_CONVERSIONS = Hash.new({ :strict => false, :proc => lambda{ |cell_value| cell_value } }).freeze
```

**Comment by tooky** [comment]
I believe this is fixed by 093ae4e19b7fadf1c39ae77a084f48da5f9c8f28.

@mattwynne we should probably release a new version with this fix.

**Comment by tooky** [comment]
@jfinkhaeuser are you able to try using the current HEAD?

You can specify `gem 'cucumber', github: 'cucumber/cucumber'` in a Gemfile.

Thanks for reporting this.

**Comment by jfinkhaeuser** [comment]
Yes, that seems to fix it just as well.

**Comment by mattwynne** [comment]
Do it tooky, if you have time!

Typed with my Thumbs.

**Comment by pritpalm** [comment]
Is this fix avaialbe now. I just installed cucumber 2.0.0.rc.3 for "embed" fix for json. Per @tooky suggestion I added require 'forwardable' to data_table.rb, that seems to fix it. I run my tests on CI/CD, that has node attached where tests are executed. I dont have access to that box, so badly need this fix.

**Comment by brasmusson** [comment]
@pritpalm Yes, cucumber 2.0.0.rc.4 was released a [couple of weeks ago](https://groups.google.com/forum/#!searchin/cukes/ann|sort:date/cukes/cQX6iyCj6dA/lPTKzEVA7DoJ).
