### ISSUE TITLE
gherkin/javascript: NoSuchLanguageException: if location is undefined, GherkinException thrown

### ISSUE THREAD

**Issue by epresi** [cucumber/cucumber#808]
## Summary

We would like to parse a feature file with a dialect provided by a user. We do not know if this dialect is valid or not. Our expectations were that `gherkin` will throw the `NoSuchLanguageException`, but we received another exception.

## Expected Behavior

When throwing the `NoSuchLanguageException` exception, `gherkin` should not run into other exceptions.
Outcome should be: 
> Language not supported: en-US

## Current Behavior

Constructor of `TokenMatcher` calls [reset](https://github.com/cucumber/cucumber/blob/69fdf8ec34a8a89dfd4b97b579e9b173a47b4c57/gherkin/javascript/src/TokenMatcher.ts#L18), which then try to [change the dialect](https://github.com/cucumber/cucumber/blob/69fdf8ec34a8a89dfd4b97b579e9b173a47b4c57/gherkin/javascript/src/TokenMatcher.ts#L33).
The [changeDialect ](https://github.com/cucumber/cucumber/blob/69fdf8ec34a8a89dfd4b97b579e9b173a47b4c57/gherkin/javascript/src/TokenMatcher.ts#L21) receives a `location` as parameter, which is optional, and not provided by the `reset`. If `gherkin` is not able to find the dialect, it tries to throw `NoSuchLanguageException`.
In the end, [location is used](https://github.com/cucumber/cucumber/blob/69fdf8ec34a8a89dfd4b97b579e9b173a47b4c57/gherkin/javascript/src/Errors.ts#L23) to display the line and column, however it was not provided to the `changeDialect`. 
Because `location` is `undefined`, we receive `GherkinException` instead of `NoSuchLanguageException`.
~~~
TypeError: Cannot read property 'line' of undefined
    at Function.GherkinException._create (***\node_modules\gherkin\dist\src\Errors.js:34:32)
    at Function.NoSuchLanguageException.create (***\node_modules\gherkin\dist\src\Errors.js:117:21)
    at TokenMatcher.changeDialect (***\node_modules\gherkin\dist\src\TokenMatcher.js:31:52)
    at TokenMatcher.reset (***\node_modules\gherkin\dist\src\TokenMatcher.js:38:18)
    at new TokenMatcher (***\node_modules\gherkin\dist\src\TokenMatcher.js:26:14)
    at Object.generateMessages [as default] (***\node_modules\gherkin\dist\src\stream\generateMessages.js:54:50)    
    at ParserMessageStream._transform (***\node_modules\gherkin\dist\src\stream\ParserMessageStream.js:45:57)       
    at ParserMessageStream.Transform._read (_stream_transform.js:189:10)
    at ParserMessageStream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:431:12)
~~~

## Steps to Reproduce (for bugs)

1. Set the `defaultDialect` of the `IGherkinOptions` to a not valid one. (e.g.: "en-US")
2. Use this `gherkinOptions` with the feature file, and call any of the methods (`fromSources`, `fromPaths`, `fromStream`)

## Context & Motivation

We would like to parse a feature file, and let cucumber decide whenever a dialect is valid, or not.

## Your Environment

* cucumber Version used: 6.0.5
* Gherkin Version used: 8.2.0

**Comment by aslakhellesoy** [comment]
Thanks for reporting this @epresi. Would you be able to submit a pull request with a fix for this?
