### ISSUE TITLE
Issue with have_content inside within_frame

### ISSUE THREAD

**Issue by joaomilho** [cucumber/cucumber#829]
First, I'm not sure this is a cucumber or a capybara or even a poltergeist issue, but I'm sure you can help.

I'm using ruby 2.1.2p95 and tested it both on cucumber pre 2.0.0 and 2.0.0.

If I run the following step, it succeeds:
```ruby
  within_frame 'my-iframe' do
    expect(page).to have_content("CORRECT CONTENT")
  end
```

But if I run the following one, instead of the expected "expected to find text..." it throws a `undefined method ```map' for nil:NilClass (NoMethodError)`:

```ruby
  within_frame 'my-iframe' do
    expect(page).to have_content("WRONG CONTENT")
  end
```

If I try the expectation outside the `within_frame` it works fine (by this I mean it fails correctly).

I also tried the following version, moving the page content outside the frame scope, and it works fine:

```ruby
  iframe_page = nil
  within_frame 'my-iframe' do
    iframe_page = page
  end
  expect(iframe_page).to have_content("WRONG FILE")
```

Thanks in advance.

**Comment by aslakhellesoy** [comment]
This is a bug tracker, not a support forum. Please use the cukes google group.

**Comment by joaomilho** [comment]
Well, it felt like a possible bug to me, but thank anyway :D

**Comment by aslakhellesoy** [comment]
Possibly, but probably not in Cucumber

**Comment by mattwynne** [comment]
I'd like to investigate this a bit more before we close it, if you don't mind Mr Hellesøy.

@joaomilho do you have a backtrace for the `undefined method`map' for nil:NilClass (NoMethodError)` error please?

**Comment by joaomilho** [comment]
Right away, Sr.
```
      undefined method `map' for nil:NilClass (NoMethodError)
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/browser.rb:60:in `find'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/driver.rb:120:in `find'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/driver.rb:124:in `find_xpath'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/node/base.rb:107:in `find_xpath'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/query.rb:110:in `block in resolve_for'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/node/base.rb:80:in `synchronize'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/query.rb:106:in `resolve_for'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/node/finders.rb:32:in `block in find'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/node/base.rb:80:in `synchronize'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/node/finders.rb:30:in `find'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/node/document.rb:23:in `text'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/queries/text_query.rb:26:in `resolve_for'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/node/matchers.rb:454:in `block in assert_text'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/node/base.rb:84:in `synchronize'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/node/matchers.rb:453:in `assert_text'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/session.rb:676:in `block (2 levels) in <class:Session>'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/rspec/matchers.rb:64:in `matches?'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-expectations-3.2.0/lib/rspec/expectations/expectation_target.rb:54:in `to'
      /Users/jm/p/on-demand-for-publishers/server/features/step_definitions/purchase_steps.rb:15:in `block (2 levels) in <top (required)>'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/session.rb:328:in `block in within_frame'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/browser.rb:130:in `within_frame'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/driver.rb:145:in `within_frame'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/session.rb:327:in `within_frame'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
      /Users/jm/p/on-demand-for-publishers/server/features/step_definitions/purchase_steps.rb:14:in `block in <top (required)>'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/core_ext/instance_exec.rb:25:in `instance_exec'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/core_ext/instance_exec.rb:25:in `block in cucumber_instance_exec'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/core_ext/instance_exec.rb:42:in `cucumber_run_with_backtrace_filtering'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/core_ext/instance_exec.rb:13:in `cucumber_instance_exec'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/rb_support/rb_step_definition.rb:106:in `invoke'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/step_match.rb:33:in `invoke'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/step_match.rb:26:in `block in activate'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/action.rb:22:in `call'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/action.rb:22:in `execute'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/step.rb:31:in `execute'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:99:in `execute'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:46:in `execute'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:24:in `test_step'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/step.rb:16:in `describe_to'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:24:in `block (3 levels) in describe_to'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:23:in `each'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:23:in `block (2 levels) in describe_to'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/filters/prepare_world.rb:22:in `call'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/filters/prepare_world.rb:22:in `block in test_case'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/around_hook.rb:16:in `call'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/around_hook.rb:16:in `execute'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:99:in `execute'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:46:in `execute'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:30:in `around_hook'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/around_hook.rb:11:in `describe_to'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:92:in `block (2 levels) in compose_around_hooks'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:93:in `call'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:93:in `compose_around_hooks'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:22:in `block in describe_to'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:17:in `call'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:17:in `test_case'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/filters/activate_steps.rb:8:in `test_case'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/filters/quit.rb:11:in `test_case'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/filter.rb:61:in `done'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/compiler.rb:23:in `done'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core/gherkin/parser.rb:31:in `done'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core.rb:29:in `parse'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-core-1.1.3/lib/cucumber/core.rb:18:in `compile'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/runtime.rb:70:in `run!'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/lib/cucumber/cli/main.rb:38:in `execute!'
      /Users/jm/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cucumber-2.0.0/bin/cucumber:9:in `<top (required)>'
      /Users/jm/.rbenv/versions/2.1.2/bin/cucumber:23:in `load'
      /Users/jm/.rbenv/versions/2.1.2/bin/cucumber:23:in `<main>'
      features/purchase.feature:16:in `Then I see the purchase confirmation page'
```

**Comment by mattwynne** [comment]
This looks to me like a bug in poltergeist then. Here’s the line that’s blowing up:

https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/browser.rb#L62 <https://github.com/teampoltergeist/poltergeist/blob/master/lib/capybara/poltergeist/browser.rb#L62>

Can you raise an issue with them? Please do get back to us if you think it is something that only happens when you run this code from Cucumber. Maybe you could try running the same test from an RSpec example?
